### ISSUE TITLE
화면캡쳐 및 저장

### ISSUE THREAD

**Issue by arako** [TaeKyuHyeon/btd-front#17]
### To-do
- [ ] 기술 스택 조사
- [ ] 성능 이슈 체크
- [ ] 세부 스펙 논의

### 참고
- 인스타 스토리: 필수크기 1080x1920(9:16) /  안전영역 1080 x 1420

**Comment by arako** [comment]
https://html2canvas.hertzen.com/

**Comment by arako** [comment]
![파일명 (1)](https://github.com/TaeKyuHyeon/btd-front/assets/14290046/c9024e14-3dc4-453b-956f-e76d60f66a27)

**Comment by arako** [comment]
3. 다운받으려는 특정요소의 위치가 position등을 통해 억지로 맞춰진 경우 정상출력이 되지 않을 수 있습니다.

 

4. div태그 내부의 img태그등 정보를 받아오는 데이터가 외부인 경우 정상적으로 출력되지 않습니다.

다른 예시 블로그 글들을 보면 http~를 통해 이미지를 가져오고 다운로드 받는다고 되어있는데, 막상 따라해보면 흰색 화면만 받아졌습니다. 서버 내부에 존재하는 이미지를 넣고 다운로드시 정상 출력되었습니다.

 https://myhappyman.tistory.com/156

**Comment by arako** [comment]
외부 이미지 불러오는 경우 프록시 설정 필요함
https://html2canvas.hertzen.com/proxy

**Comment by arako** [comment]
화면 캡쳐 라이브러리 비교
https://velog.io/@iamjoo/html2canvas-domtoImage-%ED%99%94%EB%A9%B4-%EC%BA%A1%EC%B3%90%EA%B0%80%EB%8A%A5%ED%95%9C-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC

**Comment by arako** [comment]
dom-to-image 작동 원리
https://kicksky.tistory.com/64

**Comment by arako** [comment]
@tkbro 
1. base64로 인코딩 해서 보낼때는 이미지 경로앞에 `data:image/gif;base64,` 붙여서 내려주면 좋을듯
2. 한글버전 적용된 후로 이미지생성이 고장난 느낌...?
3. 이미지 비율 1:1 말고 다르게 설정 가능한지? 지금은 잘려보여서 그림일기 비율에 맞추면 좋을듯(현재는 560*390)

**Comment by arako** [comment]
### base64 적용화면 및 잔여이슈
1. [FE] 상단 날씨 아이콘 수정 필요
2. [FE] 플리킹영역 2페이지부터 위치를 제대로 못잡음 (캡쳐하는 순간 위치값 수정하는 방식 테스트 필요)

![파일명](https://github.com/TaeKyuHyeon/btd-front/assets/14290046/e5761e23-1f6a-4fda-9312-058f2367e6f9)
![파일명 (1)](https://github.com/TaeKyuHyeon/btd-front/assets/14290046/5f1ef07e-9c0e-45d9-96e8-fecf5a5626ce)

**Comment by tkbro** [comment]
@arako 답변드립니다

> * base64로 인코딩 해서 보낼때는 이미지 경로앞에 `data:image/gif;base64,` 붙여서 내려주면 좋을듯
> * 한글버전 적용된 후로 이미지생성이 고장난 느낌...?
> * 이미지 비율 1:1 말고 다르게 설정 가능한지? 지금은 잘려보여서 그림일기 비율에 맞추면 좋을듯(현재는 560*390)

1. 원하는 포맷을 알려주면 감사하겠음. (이미지 여러개일때, 한개일때 차이)
2. 프롬프트 깎기는 추후에 좀 더 연구해보겠음.
3. `이미지 가로 크기, 8의 배수여야 함
(단위: 픽셀, 기본값: 512, 최소: 384, 최대 640)`
api 스펙이어서 해당 크기 기준으로 좋은 비율 제안해주면 api 에 적용토록 하겠음

확인부탁드립니다.

**Comment by arako** [comment]
@tkbro 
1. 한개일때 여러개일때 구분 없이 동일하게 image 주소 앞에 스트링으로 `data:image/png;base64,`를 앞에 붙여주시면 됩니다. 고정 스트링이 추가되는 형태이므로 FE에서 추가해도 되긴 하지만, 형태 변경시 base64인지 아닌지 판단이 어렵기 때문에 추후 확장성을 고려해 바로 src로 삽입할 수 있는 형태가 좋을것같습니다.

2.  👌

3. 560x392로 하면 위아래로 1픽셀정도 잘리는거라 괜찮을것같습니다~ 세로 크기도 8의 배수로 맞췄는데, 세로는 8의 배수가 아니어도 되면 390으로 내려주는게 best!
